server:
#  servlet:
#    session:
#      timeout: 80s
  port: 8080

spring:
  application:
    name: session
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/

